server:
  port: 8081

spring:
  application:
    name: user-service

keycloak:
  server-url: http://localhost:8080
  realm: user_service
  client-id: springBootApplication
  client-secret: KGgfgCKmtW8fExfSwDt9wJLqkFT6xCpY
  admin:
    username: admin
    password: admin

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
