server:
  port: 8081

spring:
  application:
    name: user-service
  data:
    redis:
      host: redis
      port: 6379
      password: admin

keycloak:
  server-url: http://keycloak:8080
  realm: user_service
  client-id: springBootApplication
  client-secret: zlwI6cE3o3Wt7lUR25AzkmQM6NRaHVVq
  admin:
    username: admin
    password: admin

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/
