server:
  port: 8082

spring:
  application:
    name: order-service

  datasource:
    url: jdbc:postgresql://localhost:5432/orders_db
    username: admin
    password: admin
    driver-class-name: org.postgresql.Driver

  jpa:
    properties:
      hibernate:
        format_sql: true
        ddl-auto: none
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true

  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      acks: all          # at-least-once
      retries: 3
      properties:
        spring.json.add.type.headers: false
        enable.idempotence: true
  liquibase:
    change-log: classpath:/changelog/changelog-master.xml
  data:
    redis:
      host: localhost
      port: 6379
      password: admin

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
